import Foundation

// MARK: - GigiCherriDSL — translation layer
//
// Apple FM @Generable produces structured Arguments (title + actionsJSON).
// This file translates that into Cherri DSL source code that compiles on
// the Mac signing server.
//
// Why an intermediate translation:
//   - Apple FM constrained decoding works best with simple schemas
//     (strings + JSON), not free-form code generation
//   - We bound which Cherri actions are available (the "vocabulary") to
//     prevent the model hallucinating actions that don't exist in Cherri
//   - User-facing previews of the generated DSL can be shown if needed
//
// Vocabulary: subset of Cherri actions safe for AI generation. Each entry
// maps a logical action name to a Cherri DSL template with placeholders.
// Apple FM picks from this list via constrained decoding; the iOS code
// substitutes the parameters and emits valid Cherri source.

struct CherriActionSpec: Codable {
    /// Logical action name (must match a key in CHERRI_VOCABULARY).
    let action: String
    /// String parameters keyed by their Cherri argument name.
    /// Examples: { "text": "Hello" } for showResult, { "seconds": "5" } for wait.
    let params: [String: String]
}

enum GigiCherriDSL {

    // MARK: - Vocabulary

    /// Available Cherri actions Apple FM can choose from. Keep small + curated
    /// to avoid hallucinated actions. Each entry: action name → Cherri DSL
    /// template using ${paramName} placeholders that get substituted.
    ///
    /// IMPORTANT: action names MUST match Cherri's exact action names from the
    /// Cherri stdlib (actions/basic.cherri, actions/scripting.cherri, etc.).
    /// See https://github.com/electrikmilk/cherri/tree/main/actions.
    static let CHERRI_VOCABULARY: [String: String] = [
        // Output
        "showResult":        #"show(${text})"#,
        "showNotification":  #"showNotification(${text})"#,
        "speakText":         #"speakText(${text})"#,

        // Timing
        "waitSeconds":       #"wait(${seconds})"#,

        // Clipboard
        "setClipboard":      #"setClipboard(${text})"#,
        "getClipboard":      #"getClipboard()"#,

        // Light / torch (system)
        "torchOn":           #"setBrightness(1)\ntorch()"#,
        "torchOff":          #"torch()"#,

        // Audio / music
        "playMusic":         #"playMusic()"#,
        "pauseMusic":        #"pauseMusic()"#,
        "skipForward":       #"skipForward()"#,
        "skipBackward":      #"skipBackward()"#,

        // HomeKit scene (most common smart-home request)
        "homeKitScene":      #"runScene(${scene})"#,

        // Focus mode
        "setFocus":          #"setFocus(${mode})"#,
        "turnOffFocus":      #"turnOffFocus()"#,

        // Open app
        "openApp":           #"openApp(${appName})"#,

        // Volume
        "setVolume":         #"setVolume(${level})"#
    ]

    // MARK: - Translation

    /// Translates Apple FM's title + actions[] into a complete Cherri DSL
    /// source file ready to be compiled by `cherri` on the Mac.
    /// Returns nil if any action is not in the vocabulary (caller decides
    /// whether to surface the error or fall back to share sheet).
    static func translate(title: String, actions: [CherriActionSpec]) -> String? {
        guard !actions.isEmpty else { return nil }

        var lines: [String] = []

        // Header comment for debugging (cherri ignores comments)
        let cleanTitle = title.trimmingCharacters(in: .whitespacesAndNewlines)
        if !cleanTitle.isEmpty {
            lines.append("// \(cleanTitle)")
            lines.append("// Generated by GIGI via Apple FM \(Date().ISO8601Format())")
            lines.append("")
        }

        // Translate each action
        for spec in actions {
            guard let template = CHERRI_VOCABULARY[spec.action] else {
                // Unknown action — abort. Caller falls back.
                GigiDebugLogger.log("GigiCherriDSL: unknown action '\(spec.action)' — abort translation")
                return nil
            }
            let rendered = substitute(template: template, params: spec.params)
            lines.append(rendered)
        }

        return lines.joined(separator: "\n")
    }

    /// Replaces ${paramName} placeholders with the corresponding values,
    /// quoting strings appropriately for Cherri syntax. Unknown placeholders
    /// in the template are left as empty strings to fail closed (the cherri
    /// compiler will reject malformed code, surfacing the error cleanly).
    private static func substitute(template: String, params: [String: String]) -> String {
        var result = template
        // Find all ${name} placeholders
        let placeholderPattern = #"\$\{([a-zA-Z_][a-zA-Z0-9_]*)\}"#
        guard let regex = try? NSRegularExpression(pattern: placeholderPattern) else {
            return template
        }
        let nsRange = NSRange(result.startIndex..<result.endIndex, in: result)
        let matches = regex.matches(in: result, range: nsRange).reversed()

        for match in matches {
            guard let nameRange = Range(match.range(at: 1), in: result),
                  let fullRange = Range(match.range(at: 0), in: result) else { continue }
            let placeholderName = String(result[nameRange])
            let raw = params[placeholderName] ?? ""
            let formatted = formatValue(raw, forPlaceholder: placeholderName)
            result.replaceSubrange(fullRange, with: formatted)
        }
        return result
    }

    /// Decides how to format a parameter value based on the placeholder name.
    /// String-like placeholders get quoted; numeric placeholders pass through.
    private static func formatValue(_ raw: String, forPlaceholder name: String) -> String {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        // Numeric placeholders: seconds, level (volume 0-100), brightness
        let numericPlaceholders: Set<String> = ["seconds", "level", "brightness", "minutes"]
        if numericPlaceholders.contains(name) {
            // Use as-is, with a fallback to 0 if not numeric.
            if Double(trimmed) != nil { return trimmed }
            return "0"
        }
        // String — escape inner double quotes and wrap.
        let escaped = trimmed.replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }
}
