blank_issues_enabled: false
contact_links:
  - name: Domanda generica / discussione
    url: https://github.com/Building-addicts/GIGI/discussions
    about: Per domande aperte o discussioni che non sono ancora una issue concreta.
